### ISSUE TITLE
Continue training a model from a checkpoint with same hash code

### ISSUE THREAD

**Issue by zhaobozb** [BorealisAI/lite_tracer#1]
If I want to continue training a model from previous saved checkpoint, the code will assign a new hash code to the experiment. However, it is perferable to have the same hash code in such scenario.

**Comment by yanshuaicao** [comment]
It is a design decision to have a different hash code. Basically the inputs that produce the first experiment are different from the inputs to the second continuation experiment. You can use a str note field for book keeping for now, or some other field that specifies if there's a previous model to load. This allows you to filter and search based on this attribute.

**Comment by yanshuaicao** [comment]
It is possible to modify the format of the hash code to make it easier to read off any continuation that might have happened if there's enough demand for that, I could add this feature

**Comment by zhaobozb** [comment]
Thanks for your explanation. That sounds reasonable.
It will be better to add some interpretability along with the hash code if possible :)

And, thanks for the useful code.

**Comment by yanshuaicao** [comment]
No problem! Glad it's useful. 
So right now the hash code itself actually has 2 parts, a base and a delta, any uncommited changes get hashed to the delta portion, and base + command line arguments are represented in the base portion. (I'll add more documentation on this)
So I guess there is some limited interpretability, but I also don't want to make the names too long. 

If you use lite_trace.py to do reverse lookup, it's more human readable.
