### ISSUE TITLE
Infinite untracked directory generation

### ISSUE THREAD

**Issue by danrecoskie** [BorealisAI/lite_tracer#15]
I've encountered an odd interaction involving git which resulted the creation of an infinite sequence of directories (and a `shutil.Error` about a filename being too long). I think this is the order that caused the issue:
1. I ran a lite_tracer script in a directory with no git tracked files (which created an `lt_records` directory).
2. I then added my script file to my git repository.
3. I re-ran the script and got a warning about untracked files in the current directory.
4. Since `lt_records` wasn’t tracked by git, it was added to the `untracked` directory in the experiment directory. This seems to be where the recursive loop occurred, since `lt_records` itself contains the `untracked` directory.
I was able to get around this by adding `lt_records` to my `.gitignore` file.

**Comment by jskang** [comment]
Thank you for reporting! I'll put up a fix asap.

**Comment by jskang** [comment]
Fixed with #16
