### ISSUE TITLE
lite_trace.py broken with lists of arguments.

### ISSUE THREAD

**Issue by mkschleg** [BorealisAI/lite_tracer#4]
This seems to be really handy for a light-weight solution for tracking experiments. There is just a problem I encountered almost immediately: lite_trace.py doesn't work when an argument takes a list of parameters.

The issue is when the argument string is split, as it is assumed to split on spaces. We will probably need a more specialized string splitting mechanism if you want this to be general purpose.

**Comment by mkschleg** [comment]
Easiest fix is to remove spaces from the format in args2str for the searchable arguments.

**Comment by zhaobozb** [comment]
Also, there is a parsing problem if the arguments contain a colon, e.g. designating a gpu device "cuda:0" in the arguments, although it can easily be prevented by avoiding using a colon.

**Comment by jskang** [comment]
#6 Fixed both issues with list and colon
