### ISSUE TITLE
Same hashcode with different git labels

### ISSUE THREAD

**Issue by zhaobozb** [BorealisAI/lite_tracer#5]
Currently, the hashcode is generated based on the command line arguments and untracked files. If I run two versions of code (i.e. having different git labels) with the same command line arguments, and without untracked files,  it will generate the same hashcode. Should the hashcode also consider the changing of git label?

**Comment by yanshuaicao** [comment]
Thank you for pointing this out. It was indeed a small bug introduced when I refactored the code for release. The design intention was indeed for git label to affect the hash. Basically the line 

> setattr(args, GIT_FIELD, git_label)

should come before 

> hash_code = args2hash(args, short=self.short_hash)

It's fixed now. Thanks again!
